### ISSUE TITLE
pufff

### ISSUE THREAD

**Issue by Newbytee** [darltrash/metahome#2]
pufffffff

icinsluvely not working with gl 3

puf i u se mesa 2 and only opengl 1 is implemnted...........

puffffff no template

**Comment by darltrash** [comment]
@Newbytee LMAOOOOO

**Comment by darltrash** [comment]
@Newbytee thanks man, this has been a truly revealing experience 👍

**Comment by mckaygerhard** [comment]
FUUU FUFUFUFUFUFUFUFUFUF !@#$&!@#($&!@#    >/*

**Comment by mckaygerhard** [comment]
you two guys are just envy ok.. ! and ok is not Ogl supoprted cos i pretty young software

**Comment by darltrash** [comment]
> you two guys are just envy ok.. ! and ok is not Ogl supoprted cos i pretty young software

Nah i didnt support it YET because sokol does not support it, but there are plans to do so
